### ISSUE TITLE
Enhancement: add environment type to bar

### ISSUE THREAD

**Issue by robbieaverill** [SilbinaryWolf/silverstripe-stagingbar#1]
Eg display whether the environment type is dev, test or live.

**Comment by silbinarywolf** [comment]
This bar is meant to be client-focused so that when they're viewing a draft, it's more obvious. I'm not sure I want to expose them to a what a developer wants to see.

What's your use case?

**Comment by robbieaverill** [comment]
Fair play! Perhaps could still be useful for a client if they are on a staging site to see that, nothing if live I suppose. Just an idea.
